/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2ef7eb89-3c95-47c5-b977-efff20332722",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rzyZC5Lov",
    "aws_user_pools_web_client_id": "2lmb87arg2mlja3ul4nhvo6fjq",
    "oauth": {}
};


export default awsmobile;
